### PR TITLE
Test

### PR DESCRIPTION
**Pull request by daanschipper**
'hello' should be 'Hello World.'

### CODE REVIEW

**Comment by ahovanesyan** [comment]
DIS IS A GOOD CHANGE MA MAN. 10/10

**Comment by jordyw** [comment]
Looks Nice!

**Comment by StefanBoodt** [comment]
The updated string to write makes the code much clearer. Now it looks even more like an Hello World program. I really think it is good to test this.

**Comment by Tomas2h** [comment]
ik vind helemaal mooi

**Pull request merged**
